apiVersion: v1
kind: Service
metadata:
  name: checklist-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
      protocol: TCP
  selector:
    app: service