apiVersion: v1
kind: Pod
metadata:
  name: checklist-service
  labels:
    app: service
spec:
  containers:
    - name: checklist-service-ctr
      image: jhallat/checklist-service:0.0.1
      ports:
        - containerPort: 5000
  imagePullSecrets:
    - name: regcred      